apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: microservices-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-svc:8761/eureka/"
            - name: JWT_SECRET
              value: "u6rckmOPVwT9OuoWZf9lZtabfM6TTRGTYiS6OQ4Nkb8="
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi