apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: microservices-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: rfgualotuna/authservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://cockroachdb-svc:26257/auth_db?user=root&password="
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-svc:8761/eureka/"
            - name: JWT_SECRET
              value: "u6rckmOPVwT9OuoWZf9lZtabfM6TTRGTYiS6OQ4Nkb8="
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi